
version: 2

sources:
  - name: raw
    database: raw_db  # Replace with the actual database name
    schema: raw_schema      # Replace with the schema name
    tables:
      - name: customers
      - name: orders
      - name: products

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
